export default {
  SET_USER: "SET_USER",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_LATEST_ORDER: "SET_LATEST_ORDER",
  SET_LAST_ORDER_COUNTS: "SET_LAST_ORDER_COUNTS",
  SET_MENU_OPTIONS: "SET_MENU_OPTIONS",
  SET_MESSAGES: "SET_MESSAGES",
  SET_EMPLOYEE: "SET_EMPLOYEE",
  SET_ORDERS: "SET_ORDERS",
};
